import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import NavLinks from "@/components/nav/nav-links";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-5 bg-zinc-800`}>
        <header className="mb-5">
          <NavLinks />
        </header>
        {children}
      </body>
    </html>
  );
}
